Update config.schema.json
0x5e/tuya-homebridge pull request #282
Opened 2023-04-17 12:53 UTC by donavanbecker

- Add Name config so that name is used in the logs instead of the full plugin name.
- removed default for type on deviceoverridee as it was inputting "Boolean" every time you save config

2023-04-17 16:07 UTC, 0x5e requested changes

2023-04-17 16:07 UTC, 0x5e commented on config.schema.json
> +        "type": "string",
the file is using tab and L9-L12 you committed is space

2023-04-17 16:08 UTC, 0x5e commented
thanks @donavanbecker , there's some issue with tab & space, others are okay :)

2023-04-17 16:11 UTC, 0x5e commented
I didn't know I can update your branch... is okay now.... thanks again!

2023-04-17 16:11 UTC, 0x5e approved these changes

2023-04-17 16:12 UTC, merged

2023-04-17 16:21 UTC, donavanbecker commented
I will be posting some more changes soon :)

2023-04-18 19:08 UTC, donavanbecker commented
See #285 and #283